### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by han-liu** [qysgithubopen/GSS#1]
Dear authors, congrats on the great work. I wonder if the codes will be released to reproduce the results. Thanks.

**Comment by qysgithubopen** [comment]
> Dear authors, congrats on the great work. I wonder if the codes will be released to reproduce the results. Thanks.

Hi,

I apologize for not being able to provide you with the code at this time.

According to the requirements of our program, the code needs to be released after the journal version is published.
